### ISSUE TITLE
Filtered export of Trac instances

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/tractive#34] opened 2021-09-21 03:52 UTC
From @rjsparks :

> mailarchive has its own svn repo, but the tickets are tracked in the ietfb trac instance with tickets with components that start with MailArchive:
>
> https://trac.ietf.org/trac/ietfdb/query?component=MailArchive%3A+ArchiveContents&or&component=MailArchive%3A+User+Interface&group=priority&col=id&col=summary&col=component&col=type&col=status&col=priority&col=milestone&col=reporter&report=36&desc=1&order=id

These tickets are intended to go into a repository, e.g. https://github.com/ietf-ribose/mailarch . 

In Tractive we should have a command that does this.

**Comment by ronaldtse** [comment] 2021-09-21 06:04
It's probably time for us to create a GitHub Actions workflow that extract Trac information into exported files to test.

**Comment by HassanAkbar** [comment] 2021-09-22 14:19
@ronaldtse 
In this case there will be missing tickets on Github and the mapping will not be one to one e.g. the first `Ticket ID` in trac db having `MailArchive` in component is `1068` so the `Github Issue#` `1` map to ticket `1068` in trac. 

Firstly, I will have generate a different mapping Trac <-> Github as we both Trac `Ticket ID` can be different from Github `Issue #`.
But this will also cause another issue because in trac tickets there are references to other tickets like `Fixes #123` or `Duplicate of #123` etc. those will become invalid. This will be a bit complex/costly to take care.

One possible solution is to mantaing one-to-one mapping by creating dummy `closed` Github issue with some "Specific Description". What do you suggest ?

**Comment by HassanAkbar** [comment] 2021-09-22 14:36
> It's probably time for us to create a GitHub Actions workflow that extract Trac information into exported files to test.

Just for confirmation, we are already comparing ticket payload which will be exported [here](https://github.com/ietf-ribose/tractive/blob/master/spec/tractive_spec.rb#L12). 
But we can add a test case if this payload is exported and can be imported for GitHub issue creation correctly?

**Closed** 2021-09-23 14:47 UTC
Labels: enhancement
